#!/usr/bin/env python3
"""
Build the Step-1 stock-level raw-data + sector-classification CSV.

This script keeps the official daily raw data untouched. It reads:
- data/stock_data.csv
- data/hs300_stock_list.csv
- a stock industry mapping CSV

Then it outputs one row per stock. The final column is always 板块划分.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable

import pandas as pd


REPO_ROOT = Path(__file__).resolve().parent
DEFAULT_EXTERNAL_INDUSTRY_CSV = Path(
    "/Users/xuzijian/Desktop/竞赛/bigdata_challenge/data/raw/stock_industry.csv"
)


SECTOR_BY_INDUSTRY_PREFIX = {
    # 消费：食品饮料、医药生物、农林牧渔、社会服务、美容护理、纺织服饰、轻工制造、商贸零售
    "A03": "消费",
    "C13": "消费",
    "C14": "消费",
    "C15": "消费",
    "C19": "消费",
    "C27": "消费",
    "F52": "消费",
    "L72": "消费",
    "M73": "消费",
    "Q84": "消费",
    # 科技（TMT）：电子、计算机、传媒、通信
    "C39": "科技（TMT）",
    "I63": "科技（TMT）",
    "I64": "科技（TMT）",
    "I65": "科技（TMT）",
    "R87": "科技（TMT）",
    # 金融地产：银行、非银金融、房地产
    "J66": "金融地产",
    "J67": "金融地产",
    "J68": "金融地产",
    "J69": "金融地产",
    "K70": "金融地产",
    # 周期：有色、化工、石油石化、钢铁、煤炭、建材
    "B06": "周期",
    "B07": "周期",
    "B09": "周期",
    "B11": "周期",
    "C26": "周期",
    "C29": "周期",
    "C30": "周期",
    "C31": "周期",
    "C32": "周期",
    # 制造：电力设备、机械设备、国防军工、汽车
    "C34": "制造",
    "C35": "制造",
    "C36": "制造",
    "C37": "制造",
    "C38": "制造",
    # 基建与公用：公用事业、交通运输、建筑装饰、环保
    "D44": "基建与公用",
    "D45": "基建与公用",
    "E48": "基建与公用",
    "G53": "基建与公用",
    "G54": "基建与公用",
    "G55": "基建与公用",
    "G56": "基建与公用",
    "G60": "基建与公用",
}

# Stock-specific overrides for broad CSRC industries that contain mixed business models.
SECTOR_BY_STOCK_CODE = {
    "002027": "科技（TMT）",  # 分众传媒：广告传媒，按 TMT/传媒归类
}


def normalize_code(value: object) -> str:
    text = str(value).strip()
    text = text.replace("sh.", "").replace("sz.", "")
    if text.endswith(".0"):
        text = text[:-2]
    return text.zfill(6)


def parse_dates(series: pd.Series) -> pd.Series:
    return pd.to_datetime(series, errors="coerce", format="mixed")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build one-stock-one-row Step-1 raw data and sector classification CSV."
    )
    parser.add_argument(
        "--stock-data",
        type=Path,
        default=REPO_ROOT / "data" / "stock_data.csv",
        help="Official daily raw stock CSV generated by get_stock_data.py.",
    )
    parser.add_argument(
        "--hs300-list",
        type=Path,
        default=REPO_ROOT / "data" / "hs300_stock_list.csv",
        help="Official HS300 constituent CSV.",
    )
    parser.add_argument(
        "--industry-csv",
        type=Path,
        default=None,
        help="Industry mapping CSV. If omitted, the script tries data/stock_industry.csv, then the local Step-1 raw source.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=REPO_ROOT / "data" / "step1_stock_raw_sector.csv",
        help="Output CSV path.",
    )
    return parser.parse_args()


def first_existing_path(paths: Iterable[Path]) -> Path | None:
    for path in paths:
        if path.exists():
            return path
    return None


def resolve_industry_csv(explicit_path: Path | None) -> Path:
    if explicit_path is not None:
        if not explicit_path.exists():
            raise FileNotFoundError(f"Industry CSV not found: {explicit_path}")
        return explicit_path

    industry_path = first_existing_path(
        [
            REPO_ROOT / "data" / "stock_industry.csv",
            DEFAULT_EXTERNAL_INDUSTRY_CSV,
        ]
    )
    if industry_path is None:
        raise FileNotFoundError(
            "No industry mapping CSV found. Provide --industry-csv or place one at data/stock_industry.csv."
        )
    return industry_path


def read_stock_data(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path, encoding="utf-8-sig", dtype={"股票代码": str})
    required = {
        "股票代码",
        "日期",
        "开盘",
        "收盘",
        "最高",
        "最低",
        "成交量",
        "成交额",
        "振幅",
        "涨跌额",
        "换手率",
        "涨跌幅",
    }
    missing = sorted(required - set(df.columns))
    if missing:
        raise ValueError(f"stock data missing columns: {missing}")

    df["股票代码"] = df["股票代码"].map(normalize_code)
    df["日期_dt"] = parse_dates(df["日期"])
    df = df.dropna(subset=["日期_dt"]).copy()

    numeric_cols = ["开盘", "收盘", "最高", "最低", "成交量", "成交额", "振幅", "涨跌额", "换手率", "涨跌幅"]
    for col in numeric_cols:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    return df.sort_values(["股票代码", "日期_dt"])


def read_hs300_list(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path, encoding="utf-8-sig", dtype=str)
    required = {"updateDate", "code", "code_name"}
    missing = sorted(required - set(df.columns))
    if missing:
        raise ValueError(f"HS300 list missing columns: {missing}")

    return pd.DataFrame(
        {
            "股票代码": df["code"].map(normalize_code),
            "股票名称": df["code_name"].str.strip(),
            "成分股更新日期": df["updateDate"].str.strip(),
        }
    )


def read_industry(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path, encoding="utf-8-sig", dtype=str)
    required = {"updateDate", "code", "industry", "industryClassification"}
    missing = sorted(required - set(df.columns))
    if missing:
        raise ValueError(f"industry mapping missing columns: {missing}")

    return pd.DataFrame(
        {
            "股票代码": df["code"].map(normalize_code),
            "行业来源日期": df["updateDate"].str.strip(),
            "原始行业": df["industry"].fillna("").str.strip(),
            "行业分类口径": df["industryClassification"].fillna("").str.strip(),
        }
    )


def classify_sector(stock_code: str, industry: str) -> str:
    if stock_code in SECTOR_BY_STOCK_CODE:
        return SECTOR_BY_STOCK_CODE[stock_code]
    prefix = str(industry).strip()[:3]
    return SECTOR_BY_INDUSTRY_PREFIX.get(prefix, "未匹配")


def window_return_pct(group: pd.DataFrame, window: int) -> float | None:
    window_df = group.tail(window)
    if len(window_df) < 2:
        return None
    first_close = window_df["收盘"].iloc[0]
    last_close = window_df["收盘"].iloc[-1]
    if pd.isna(first_close) or first_close == 0 or pd.isna(last_close):
        return None
    return (last_close / first_close - 1) * 100


def summarize_one_stock(group: pd.DataFrame) -> dict[str, object]:
    group = group.sort_values("日期_dt")
    latest = group.iloc[-1]
    row: dict[str, object] = {
        "raw_起始日期": group["日期_dt"].min().strftime("%Y-%m-%d"),
        "raw_结束日期": group["日期_dt"].max().strftime("%Y-%m-%d"),
        "raw_交易日数": int(len(group)),
        "最新日期": latest["日期_dt"].strftime("%Y-%m-%d"),
        "最新开盘": latest["开盘"],
        "最新收盘": latest["收盘"],
        "最新最高": latest["最高"],
        "最新最低": latest["最低"],
        "最新成交量": latest["成交量"],
        "最新成交额": latest["成交额"],
        "最新振幅": latest["振幅"],
        "最新涨跌额": latest["涨跌额"],
        "最新换手率": latest["换手率"],
        "最新涨跌幅": latest["涨跌幅"],
    }

    for window in (5, 20, 60):
        window_df = group.tail(window)
        row[f"近{window}日收益率"] = window_return_pct(group, window)
        row[f"近{window}日成交量均值"] = window_df["成交量"].mean()
        row[f"近{window}日成交额均值"] = window_df["成交额"].mean()
        row[f"近{window}日换手率均值"] = window_df["换手率"].mean()
        row[f"近{window}日涨跌幅波动率"] = window_df["涨跌幅"].std()

    return row


def build_output(stock_data: pd.DataFrame, hs300: pd.DataFrame, industry: pd.DataFrame) -> pd.DataFrame:
    summary_rows = []
    for stock_code, group in stock_data.groupby("股票代码", sort=True):
        row = {"股票代码": stock_code}
        row.update(summarize_one_stock(group))
        summary_rows.append(row)

    summary = pd.DataFrame(summary_rows)
    output = hs300.merge(summary, on="股票代码", how="left")
    output = output.merge(industry, on="股票代码", how="left")
    output["板块划分"] = [
        classify_sector(stock_code, industry_name)
        for stock_code, industry_name in zip(output["股票代码"], output["原始行业"], strict=False)
    ]

    raw_columns = [
        "股票代码",
        "股票名称",
        "成分股更新日期",
        "raw_起始日期",
        "raw_结束日期",
        "raw_交易日数",
        "最新日期",
        "最新开盘",
        "最新收盘",
        "最新最高",
        "最新最低",
        "最新成交量",
        "最新成交额",
        "最新振幅",
        "最新涨跌额",
        "最新换手率",
        "最新涨跌幅",
        "近5日收益率",
        "近5日成交量均值",
        "近5日成交额均值",
        "近5日换手率均值",
        "近5日涨跌幅波动率",
        "近20日收益率",
        "近20日成交量均值",
        "近20日成交额均值",
        "近20日换手率均值",
        "近20日涨跌幅波动率",
        "近60日收益率",
        "近60日成交量均值",
        "近60日成交额均值",
        "近60日换手率均值",
        "近60日涨跌幅波动率",
        "行业来源日期",
        "原始行业",
        "行业分类口径",
        "板块划分",
    ]
    return output[raw_columns]


def validate_output(df: pd.DataFrame) -> None:
    if df.columns[-1] != "板块划分":
        raise ValueError("Final column must be 板块划分.")
    if df["股票代码"].duplicated().any():
        duplicates = df.loc[df["股票代码"].duplicated(), "股票代码"].tolist()
        raise ValueError(f"Duplicated stock codes: {duplicates[:10]}")
    if df["板块划分"].eq("未匹配").any():
        unmatched = df.loc[df["板块划分"].eq("未匹配"), ["股票代码", "股票名称", "原始行业"]]
        raise ValueError(f"Unmatched sector rows:\n{unmatched.to_string(index=False)}")
    if df["raw_交易日数"].isna().any():
        missing = df.loc[df["raw_交易日数"].isna(), ["股票代码", "股票名称"]]
        raise ValueError(f"Stocks missing raw daily data:\n{missing.to_string(index=False)}")


def main() -> None:
    args = parse_args()
    industry_csv = resolve_industry_csv(args.industry_csv)

    stock_data = read_stock_data(args.stock_data)
    hs300 = read_hs300_list(args.hs300_list)
    industry = read_industry(industry_csv)
    output = build_output(stock_data, hs300, industry)

    # Keep numeric fields compact while preserving enough precision for later checks.
    numeric_cols = output.select_dtypes(include=["number"]).columns
    output[numeric_cols] = output[numeric_cols].round(6)

    validate_output(output)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    output.to_csv(args.output, index=False, encoding="utf-8-sig")

    print(f"output: {args.output}")
    print(f"rows: {len(output)}")
    print(f"unique stocks: {output['股票代码'].nunique()}")
    print(f"industry source: {industry_csv}")
    print("sector counts:")
    print(output["板块划分"].value_counts().to_string())


if __name__ == "__main__":
    main()
